# Generated by Django 3.2.1 on 2021-12-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_dance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dance',
        ),
    ]
